server:
  port: 8080
  servlet:
    context-path: /api
spring:
  properties:
    host-name: ${APP_HOST_NAME}
    github:
      token: ${GithubBearer}
    async:
      max-pool-size: 100
      core-pool-size: 20
    auto-upload:
      enabled: true
      period-mills: 600000 # 15 minutes
    db:
      schema: gfi
  flyway:
    enabled: true
    clean-disabled: true
    encoding: UTF-8
    locations: classpath:db/migration
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    validate-on-migrate: true
    baseline-on-migrate: true
    url: ${spring.datasource.url}
    password: ${spring.datasource.password}
    user: ${spring.datasource.username}
  application:
      name: good-first-issue-back
  datasource:
    password: SomeUselessPassword02
    url: jdbc:postgresql://${spring.properties.host-name}:5432/uj?currentSchema=${spring.properties.db.schema}
    username: idk_user
  jpa:
    hibernate:
      ddl-auto: validate

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.github.regyl.gfi.controller.dto
  type-handlers-package: com.github.regyl.gfi.typehandler